### ISSUE TITLE
Internet Provider blocks IP adress that use Wish Simulator

### ISSUE THREAD

**Issue by ReyAND11** [dzmuh97/genshin-twitch-wish#1]
Hi, can you help me? My internet provider blocks IP adress that wish simulator use for connection. As I understand it's because of some Russian IP adress, can you add some other IP adresses that program can connect? Thanks

**Comment by dzmuh97** [comment]
In version 3.0.1, proxy support for API GATE requests (currently genshinwishgate.pw) has been added via the ENV environment. To have the simulator use, for example, an HTTPS proxy for requests API GATE, you can use the following:

```cmd
set HTTPS_PROXY=http://proxy_login:proxy_pass@proxy_ip:proxy_port/
TwitchGenshinWishSim.exe
```

Naturally, replace proxy_login, proxy_pass, proxy_ip, and proxy_port with the actual data. The proxy can also be set through environment variables in the system itself.

P.S.: The proxy will only work for requests to the API GATE made by the simulator itself. On the first launch, authentication occurs in the browser. In this case, you might also want to configure the proxy settings in the browser.
