### ISSUE TITLE
Что за названия у персонажей?

### ISSUE THREAD

**Issue by vanyaindigo** [dzmuh97/genshin-twitch-wish#3]
А можно вернуть каноничные названия и звезды для персонажей? С чего вдруг Джин стала 4-кой?

**Comment by dzmuh97** [comment]
В баннерах по типу all_in_one есть как скины, так и персонажи. На Джинн есть скин "Наследие Гуннхильдр" (если речь о нем), который имеет редкость 4★ (https://genshin.honeyhunterworld.com/i_n340006/?lang=RU). Если не нужны скины в баннерах, то их можно просто удалить оттуда вручную или сделать свой баннер без скинов

**Comment by vanyaindigo** [comment]
Скины не хотелось бы удалять, но несколько странно включать в баннер стандартные скины персонажей, которые доступны по умолчанию с персонажем.

**Comment by dzmuh97** [comment]
Скины которые сейчас доступны в баннерах были добавлены в версии 2.4 как альтернативы оригинальным скинам персонажей. Всего их 4: "За вольный дух церкви" Розария, "Встреча звёзд и луны" Мона, "Наследие Гуннхильдр" Джинн и "Скаут на все сто" Эмбер. Если не хочется их видеть, то просто отредактируй баннер который используешь и удали оттуда эти названия

**Comment by vanyaindigo** [comment]
Ок, понял. Спасибо.
