### ISSUE TITLE
Цвет никак вначале другого цвета.

### ISSUE THREAD

**Issue by vanyaindigo** [dzmuh97/genshin-twitch-wish#4]
В прошлой версии и ник, и сопутствующий цвет в окне были белыми и хороши читались. Сейчас же цвет ника стал черным и я не нашел нигде в настройках возможность его менять. Не туда смотрю?

И можно сделать так, чтобы окно с настройками не вылазило каждый раз при запуске?

**Comment by dzmuh97** [comment]
Черный цвет ника при использовании команды из чата или награды за баллы канала? В тестовом режиме тоже черный цвет? Прикрепи скриншот если возможно с черным цветом и окном настроек

Сейчас нельзя, в будущих версиях планируется

**Comment by vanyaindigo** [comment]
![изображение](https://github.com/dzmuh97/genshin-twitch-wish/assets/34334385/b362621e-e1d3-44dd-ae22-476fc058ff2b)

**Comment by vanyaindigo** [comment]
Окно настроек сейчас не могу прикрепить, не у компа. Черный цвет при использовании баллов канала.

**Comment by dzmuh97** [comment]
Проблема цветов в следующем: зритель на твиче может выбрать себе цвет ника, этот цвет отображается в чате и его видит симулятор. Но если зритель использует баллы канала, то цвет его ника твич не передает, симулятор его просто не знает. 

Поэтому сейчас логика такая: если стоит галочка в "Чат Бота"->"Включить цвета", то для команд из чата цвет ника будет тем же, какой зритель поставил себе на твиче. Если галочка не стоит, то цвет ника будет такой же, как указано в "Баллы Канала"->"Цвет". Если зритель использует баллы канала, то цвет ника всегда будет такой, как указано в "Баллы Канала"->"Цвет". По умолчанию там стоит "#FFFFFF" (белый)

Если у тебя в настройках "Баллы Канала"->"Цвет" стоит "#FFFFFF", а цвет ника все равно при использовании баллов канала черный, то это баг.  Нужен будет скрин настроек симулятора или твой файл config.json, чтобы я смог повторить его у себя и начать искать где ошибка

**Comment by vanyaindigo** [comment]
Ок, как буду дома, посмотрю.

**Comment by vanyaindigo** [comment]
Все, разобрался, там действительно стоял цвет #000000, поэтому все ники были черными. Но я его таким не ставил. Выставил белый и вроде сейчас ок.
