### ISSUE TITLE
genshinwishgate.pw не доступен

### ISSUE THREAD

**Issue by vanyaindigo** [dzmuh97/genshin-twitch-wish#5]
Перестала работать авторизация на хосте genshinwishgate.pw. Закрывает соединенение с ошибкой (проблемы с сертификатом?).

**Comment by dzmuh97** [comment]
Бэкенд проекта был действительно недоступен, спасибо за информацию. Сейчас все должно работать штатно.

**Comment by vanyaindigo** [comment]
Привет, снова истек сертификат:

`Не удалось обновить токен: Cannot connect to host genshinwishgate.pw:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired`
